version: '3'
services:
  api:
    image: blaisemarvin/libraryapp
    depends_on:
      - postgres
    ports:
      - 80:8000
    # volumes:
    #   - ./:/usr/src/app
    
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=libraryapp
      - POSTGRES_USER=blaise
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: